// copyright 2017 BYU Animation

#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogBeatBoxers, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogBeatBoxersCriticalErrors, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogUInputParser, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogUMoveset, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogUFighterState, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAFighterCharacter, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogUSoloTracker, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogABBGameMode, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogBBAnimation, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogBBUI, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFretboard, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogBeatTiming, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogClashing, Log, All);